Repository Core-Foreign-Employee-Hiring/Back-end_v2, pull requests merged in 2025-09, with the labels that each got.

#40 [FEAT] 문의하기 답변 상태 조회하는 api 추가.
  src/main/java/com/forwork/backend/api/mypage/dto/response/ArchiveInquiryResponseDTO.java
  src/main/java/com/forwork/backend/api/mypage/service/EmployeeMyPageService.java
  src/main/java/com/forwork/backend/api/pass_archive/controller/PassArchiveController.java
  src/main/java/com/forwork/backend/api/pass_archive/dto/LatestInquiryResponseDTO.java
  src/main/java/com/forwork/backend/api/pass_archive/dto/PassArchiveDetailResponseDTO.java
  src/main/java/com/forwork/backend/api/pass_archive/entity/ArchiveInquiry.java
  src/main/java/com/forwork/backend/api/pass_archive/repository/ArchiveInquiryRepository.java
  src/main/java/com/forwork/backend/api/pass_archive/service/ArchiveInquiryReader.java
  src/main/java/com/forwork/backend/api/pass_archive/service/ArchiveInquiryService.java
  src/main/java/com/forwork/backend/api/pass_archive/service/PassArchiveService.java
  src/main/java/com/forwork/backend/common/response/SuccessStatus.java
Labels: FEAT, 용범

#42 [FEAT] 판매한 아카이브 그리고 작성한 아카이브 조회 구현
  src/main/java/com/forwork/backend/api/mypage/controller/EmployeeMyPageController.java
  src/main/java/com/forwork/backend/api/mypage/dto/query/ArchiveSalesCountQueryDTO.java
  src/main/java/com/forwork/backend/api/mypage/dto/response/ArchiveInquiryResponseDTO.java
  src/main/java/com/forwork/backend/api/mypage/dto/response/PurchasedArchivesPreviewResponseDTO.java
  src/main/java/com/forwork/backend/api/mypage/dto/response/SoldArchiveResponseDTO.java
  src/main/java/com/forwork/backend/api/mypage/dto/response/WrittenArchiveResponseDTO.java
  src/main/java/com/forwork/backend/api/mypage/service/EmployeeMyPageService.java
  src/main/java/com/forwork/backend/api/order/repository/OrderPassArchiveRepository.java
  src/main/java/com/forwork/backend/api/pass_archive/controller/PassArchiveController.java
  src/main/java/com/forwork/backend/api/pass_archive/dto/ArchiveInquiryResponseDTO.java
  src/main/java/com/forwork/backend/api/pass_archive/entity/ArchiveInquiry.java
  src/main/java/com/forwork/backend/api/pass_archive/repository/ArchiveInquiryRepository.java
  src/main/java/com/forwork/backend/api/pass_archive/repository/PassArchiveRepository.java
  src/main/java/com/forwork/backend/api/pass_archive/service/ArchiveInquiryReader.java
  src/main/java/com/forwork/backend/api/pass_archive/service/ArchiveInquiryService.java
  src/main/java/com/forwork/backend/api/pay/repository/PaymentRepository.java
  src/main/java/com/forwork/backend/api/pay/service/PaymentReader.java
  src/main/java/com/forwork/backend/common/response/SuccessStatus.java
Labels: FEAT, 용범

#44 [REFAC] 결제 예외 처리 리팩토링
  src/main/java/com/forwork/backend/api/pay/enums/PaymentStatus.java
  src/main/java/com/forwork/backend/api/pay/enums/TossPaymentConfirmExceptionType.java
  src/main/java/com/forwork/backend/api/pay/enums/TossPaymentStatus.java
  src/main/java/com/forwork/backend/api/pay/exception/confirm/PaymentRetryableException.java
  src/main/java/com/forwork/backend/api/pay/service/PaymentService.java
  src/main/java/com/forwork/backend/common/response/ErrorStatus.java
Labels: REFAC, 용범

#47 [FEAT] 마이페이지 정보 수정 구현
  src/main/java/com/forwork/backend/api/member/controller/MemberController.java
  src/main/java/com/forwork/backend/api/member/dto/MemberProfileResponseDTO.java
  src/main/java/com/forwork/backend/api/member/dto/MemberUpdateRequestDTO.java
  src/main/java/com/forwork/backend/api/member/entity/Member.java
  src/main/java/com/forwork/backend/api/member/service/MemberService.java
  src/main/java/com/forwork/backend/common/response/SuccessStatus.java
Labels: FEAT, 태근

#50 [FIX] 결제 승인 수정
  src/main/java/com/forwork/backend/api/pay/service/PaymentService.java
Labels: FIX, 용범

#66 [REFAC] cors 설정 변경
  src/main/java/com/forwork/backend/common/config/security/SecurityConfig.java
Labels: REFAC, 용범

#70 [FIX] 공고 상세조회 수정
  src/main/java/com/forwork/backend/api/recruit/dto/response/RecruitDetailResponseDTO.java
Labels: FIX, 용범

#74 [FIX] jwt 로그 제거
  src/main/java/com/forwork/backend/api/member/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/forwork/backend/api/member/jwt/service/JwtService.java
  src/main/java/com/forwork/backend/api/recruit/entity/Recruit.java
Labels: FIX, 용범

#78 [FEAT] 공고 삭제 구현
  src/main/java/com/forwork/backend/api/recruit/controller/RecruitController.java
  src/main/java/com/forwork/backend/api/recruit/repository/RecruitBookmarkRepository.java
  src/main/java/com/forwork/backend/api/recruit/repository/RecruitJobCategoryRepository.java
  src/main/java/com/forwork/backend/api/recruit/service/RecruitService.java
  src/main/java/com/forwork/backend/common/response/SuccessStatus.java
Labels: FEAT, 용범
